import { MODEL_MAP } from '@src/consts';
import { ModelID } from '@src/types';

import '@components/EntityCard/css/CardFooter.css';

interface CardFooterProps {
    item: string;
    prompt: string,
    date: string,
}

export const CardFooter = ({ item, prompt, date }: CardFooterProps) => {
    const [_, imageModelId, textModelId] = item.split("-");
    return (
        <div className="metadata">
            <i>prompt: {prompt}</i>
            <br />
            <i>generated by: {MODEL_MAP[imageModelId as ModelID]}</i>
            <br />
            <i>described by: {MODEL_MAP[textModelId as ModelID]}</i>
            <br />
            <i> on {date}</i>
            <br />
      </div>
    );
}